### ISSUE TITLE
Icon is too fat, looks ugly on dock

### ISSUE THREAD

**Issue by jpike88** [chenasraf/gInbox#42] opened 2015-05-25 01:49 UTC
![screen shot 2015-05-25 at 11 48 52 am](https://cloud.githubusercontent.com/assets/9585787/7790718/0ab71a70-02d4-11e5-852b-03181263d443.png)

**Comment by busseo** [comment] 2015-05-26 12:43
I agree

**Comment by jameswilson** [comment] 2015-05-27 01:15
Duplicate of #15, #25, and #28,  see pull request on #36.

PLEASE check the issue queue before posting a new issue.

**Closed** 2015-07-06 15:04 UTC
Labels: duplicate
