### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by kasik96** [chenasraf/gInbox#25] opened 2015-02-09 08:09 UTC
Hi, you use super big icon of this app and in dock it doesnt look good, so i made smaller and it look 100% better. Here it is: https://www.dropbox.com/s/t326y4t6kvclqaf/GoogleInbox.zip?dl=0

**Comment by chenasraf** [comment] 2015-02-09 09:01
@kasik96 thanks! I'll convert those and add to the project when I work on it

**Comment by jameswilson** [comment] 2015-03-17 04:39
This Is a duplicate of #28 which already has a pull request.

**Comment by chenasraf** [comment] 2015-03-19 15:35
Closing in favor of #28

**Closed by chenasraf** 2015-03-19 15:35 UTC
Labels: enhancement
