### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by inspire22** [chenasraf/gInbox#20] opened 2015-01-08 07:12 UTC
I've tried logging out and back into my google account on safari.

If I try to visit inbox.google.com on safari now though I get "Inbox only works in Google Chrome. More browsers coming soon."  Could this be the problem?

Works on my chrome browser, obviously

**Comment by chenasraf** [comment] 2015-01-11 14:05
I spoof the user agent through the app, so it's not supposed to be that problem. I'm gonna put this closed as dupe of #8, and hopefully there will be a solution soon...

**Closed by chenasraf** 2015-01-11 14:05 UTC
